export const OPEN_CART='OPEN_CART';
export const CLOSE_CART='CLOSE_CART';
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const SET_PRODUCT='SET_PRODUCT';
export const FETCH_PROUDUCT='FETCH_PRODUCT';